[package]
name = "dcaf"
version = "0.1.0"
edition = "2021"
authors = ["Falko Galperin <falko1@uni-bremen.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = ["serde/std", "ciborium/std", "serde_bytes/std", "erased-serde/std"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
ciborium = { version = "^0.2.0", default-features = false }
ciborium-io = { version = "^0.2.0", default-features = false }
coset = { git = "https://github.com/google/coset" }
serde_bytes = { version = "^0.11.5", default-features = false, features = ["alloc"] }
erased-serde = { version = "^0.3.18", default-features = false, features = ["alloc"] }
derive_builder = { version = "^0.10.2", default-features = false }

[dev-dependencies]
hex = { version = "^0.4.3", default-features = false, features = ["alloc"] }
